version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: clinic_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: clinic_management
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - clinic_network

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: clinic_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/clinic_management?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-for-production
      JWT_EXPIRE: 7d
      CLIENT_URL: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - clinic_network

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: clinic_frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - clinic_network

volumes:
  mongodb_data:
    driver: local

networks:
  clinic_network:
    driver: bridge
